/**
 * build-corpus
 *
 * Reads the hand-authored lexicons under src/content/lexicon/, validates each
 * word's part-of-speech with RiTa, computes pluralization and syllable counts,
 * and emits a frozen build artifact at src/content/generated/corpus.ts.
 *
 * Runtime MUST NOT import rita. This script is the only place rita runs.
 *
 * Usage:
 *   pnpm build-corpus
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RiTa } from "rita";

import { ADJECTIVES } from "../src/content/lexicon/adjectives.ts";
import { NOUNS } from "../src/content/lexicon/nouns.ts";

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export interface GeneratedCorpus {
  readonly nouns: readonly GeneratedNoun[];
  readonly adjectives: readonly GeneratedAdjective[];
  readonly lastBuilt: string;
}

/**
 * Treat a word as a noun if RiTa's dictionary tags it as one, or if the
 * fallback Penn Treebank tagger assigns it an `nn*` tag. isNoun alone only
 * covers words in RiTa's internal dictionary — philosophical vocabulary
 * like "syllogism", "tautology", and "lemma" is reliably tagged by pos()
 * via LTS rules even when isNoun() is false.
 */
function isNounStrict(word: string): boolean {
  if (RiTa.isNoun(word)) return true;
  const tag = posTag(word);
  return tag.startsWith("nn");
}

function isAdjectiveStrict(word: string): boolean {
  if (RiTa.isAdjective(word)) return true;
  const tag = posTag(word);
  return tag === "jj" || tag.startsWith("jj");
}

function posTag(word: string): string {
  const raw = RiTa.pos(word);
  const tag = Array.isArray(raw) ? raw[0] : raw;
  return String(tag ?? "");
}

function countSyllables(word: string): number {
  const phonemes = RiTa.syllables(word);
  if (!phonemes) return 0;
  // RiTa returns phoneme groups separated by "/" — one group per syllable.
  return phonemes.split("/").filter((s) => s.length > 0).length;
}

export function buildCorpus(
  nouns: readonly string[] = NOUNS,
  adjectives: readonly string[] = ADJECTIVES,
  now: Date = new Date()
): GeneratedCorpus {
  const badNouns = nouns.filter((w) => !isNounStrict(w));
  if (badNouns.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-nouns — fix the lexicon: ${badNouns.join(", ")}`
    );
  }

  const badAdjectives = adjectives.filter((w) => !isAdjectiveStrict(w));
  if (badAdjectives.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-adjectives — fix the lexicon: ${badAdjectives.join(", ")}`
    );
  }

  const processedNouns: GeneratedNoun[] = nouns.map((word) => {
    const plural = RiTa.pluralize(word);
    if (!plural) {
      throw new Error(`RiTa produced an empty plural for "${word}"`);
    }
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, plural, syllables };
  });

  const processedAdjectives: GeneratedAdjective[] = adjectives.map((word) => {
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, syllables };
  });

  return {
    nouns: processedNouns,
    adjectives: processedAdjectives,
    lastBuilt: now.toISOString(),
  };
}

const BANNER = [
  "// ============================================================================",
  "// DO NOT EDIT — generated by scripts/build-corpus.ts",
  "// Run `pnpm build-corpus` to regenerate this file from the lexicons.",
  "// Hand-edits will be overwritten and CI will flag stale output.",
  "// ============================================================================",
].join("\n");

export function renderCorpusModule(corpus: GeneratedCorpus): string {
  const nounLines = corpus.nouns
    .map(
      (n) =>
        `    { word: ${JSON.stringify(n.word)}, plural: ${JSON.stringify(n.plural)}, syllables: ${n.syllables} },`
    )
    .join("\n");
  const adjLines = corpus.adjectives
    .map((a) => `    { word: ${JSON.stringify(a.word)}, syllables: ${a.syllables} },`)
    .join("\n");

  return `${BANNER}

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export const GENERATED_CORPUS = {
  nouns: [
${nounLines}
  ],
  adjectives: [
${adjLines}
  ],
  lastBuilt: ${JSON.stringify(corpus.lastBuilt)},
} as const;

export type GeneratedCorpus = typeof GENERATED_CORPUS;
`;
}

function resolveOutputPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "corpus.ts");
}

/**
 * Produce the final module text for a fresh corpus, re-using the previous
 * `lastBuilt` timestamp if nothing else changed. This keeps CI diffs driven by
 * real content changes rather than wall-clock drift.
 */
export function renderStableCorpusModule(corpus: GeneratedCorpus, previous: string | null): string {
  if (previous === null) return renderCorpusModule(corpus);
  const candidateWithPrevStamp = renderCorpusModule({
    ...corpus,
    lastBuilt: extractLastBuilt(previous) ?? corpus.lastBuilt,
  });
  // If swapping in the prior timestamp reproduces the previous file exactly,
  // nothing of substance has changed — keep the old output byte-for-byte.
  if (candidateWithPrevStamp === previous) return previous;
  return renderCorpusModule(corpus);
}

function extractLastBuilt(source: string): string | null {
  const match = source.match(/lastBuilt:\s*"([^"]+)"/);
  return match?.[1] ?? null;
}

function main(): void {
  const corpus = buildCorpus();
  const target = resolveOutputPath();
  const previous = existsSync(target) ? readFileSync(target, "utf8") : null;
  const output = renderStableCorpusModule(corpus, previous);
  writeFileSync(target, output, "utf8");
  console.log(
    `[build-corpus] wrote ${corpus.nouns.length} nouns and ${corpus.adjectives.length} adjectives to ${path.relative(process.cwd(), target)}`
  );
}

// Run as CLI unless imported for testing. tsx sets import.meta.url to the
// script path when invoked directly.
const isDirectRun = (() => {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return fileURLToPath(import.meta.url) === path.resolve(entry);
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  main();
}
