/**
 * build-corpus
 *
 * Reads the hand-authored lexicons under src/content/lexicon/, validates each
 * word's part-of-speech with RiTa, computes pluralization and syllable counts,
 * and emits a frozen build artifact at src/content/generated/corpus.ts.
 *
 * Runtime MUST NOT import rita. This script is the only place rita runs.
 *
 * Usage:
 *   pnpm build-corpus
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RiTa } from "rita";

import { ADJECTIVES } from "../src/content/lexicon/adjectives.ts";
import { NOUNS } from "../src/content/lexicon/nouns.ts";
import { buildGrammars, renderStableGrammarsJson } from "./build-grammars.ts";
import { SURREALIST_FRAGMENTS, type SurrealistFragment } from "./sources/surrealist-fragments.ts";

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export interface GeneratedCorpus {
  readonly nouns: readonly GeneratedNoun[];
  readonly adjectives: readonly GeneratedAdjective[];
  readonly lastBuilt: string;
}

/**
 * Treat a word as a noun if RiTa's dictionary tags it as one, or if the
 * fallback Penn Treebank tagger assigns it an `nn*` tag. isNoun alone only
 * covers words in RiTa's internal dictionary — philosophical vocabulary
 * like "syllogism", "tautology", and "lemma" is reliably tagged by pos()
 * via LTS rules even when isNoun() is false.
 */
function isNounStrict(word: string): boolean {
  if (RiTa.isNoun(word)) return true;
  const tag = posTag(word);
  return tag.startsWith("nn");
}

function isAdjectiveStrict(word: string): boolean {
  if (RiTa.isAdjective(word)) return true;
  const tag = posTag(word);
  return tag === "jj" || tag.startsWith("jj");
}

function posTag(word: string): string {
  const raw = RiTa.pos(word);
  const tag = Array.isArray(raw) ? raw[0] : raw;
  return String(tag ?? "");
}

function countSyllables(word: string): number {
  const phonemes = RiTa.syllables(word);
  if (!phonemes) return 0;
  // RiTa returns phoneme groups separated by "/" — one group per syllable.
  return phonemes.split("/").filter((s) => s.length > 0).length;
}

export function buildCorpus(
  nouns: readonly string[] = NOUNS,
  adjectives: readonly string[] = ADJECTIVES,
  now: Date = new Date()
): GeneratedCorpus {
  const badNouns = nouns.filter((w) => !isNounStrict(w));
  if (badNouns.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-nouns — fix the lexicon: ${badNouns.join(", ")}`
    );
  }

  const badAdjectives = adjectives.filter((w) => !isAdjectiveStrict(w));
  if (badAdjectives.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-adjectives — fix the lexicon: ${badAdjectives.join(", ")}`
    );
  }

  const processedNouns: GeneratedNoun[] = nouns.map((word) => {
    const plural = RiTa.pluralize(word);
    if (!plural) {
      throw new Error(`RiTa produced an empty plural for "${word}"`);
    }
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, plural, syllables };
  });

  const processedAdjectives: GeneratedAdjective[] = adjectives.map((word) => {
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, syllables };
  });

  return {
    nouns: processedNouns,
    adjectives: processedAdjectives,
    lastBuilt: now.toISOString(),
  };
}

const BANNER = [
  "// ============================================================================",
  "// DO NOT EDIT — generated by scripts/build-corpus.ts",
  "// Run `pnpm build-corpus` to regenerate this file from the lexicons.",
  "// Hand-edits will be overwritten and CI will flag stale output.",
  "// ============================================================================",
].join("\n");

/**
 * Stable JSON rendering for the corpus data. The `.ts` accessor wraps this
 * file with types so consumers never have to know whether the data is a
 * TS module or JSON — they just import `GENERATED_CORPUS` from
 * `@/content/generated/corpus`.
 */
export function renderCorpusJson(corpus: GeneratedCorpus): string {
  return `${JSON.stringify(corpus, null, 2)}\n`;
}

/**
 * Thin TS accessor module — types + a re-export of the JSON payload.
 * Kept small and stable so hand-edits are unnecessary and diffs on
 * `corpus.ts` only happen when the schema actually changes.
 */
export function renderCorpusAccessorModule(): string {
  return `${BANNER}

import data from "./corpus.json" with { type: "json" };

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export interface GeneratedCorpus {
  readonly nouns: readonly GeneratedNoun[];
  readonly adjectives: readonly GeneratedAdjective[];
  readonly lastBuilt: string;
}

export const GENERATED_CORPUS = data as GeneratedCorpus;
`;
}

function resolveCorpusJsonPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "corpus.json");
}

function resolveCorpusAccessorPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "corpus.ts");
}

function resolveSurrealistJsonPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "surrealist.json");
}

function resolveSurrealistAccessorPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "surrealist.ts");
}

// ============================================================================
// Surrealist corpus
// ============================================================================

export interface TaggedWord {
  readonly word: string;
  readonly pos: string;
  readonly syllables: number;
}

export interface GeneratedSurrealistFragment {
  readonly id: string;
  readonly text: string;
  readonly source: string;
  readonly year: number;
  readonly derivative: boolean;
  readonly tokens: readonly string[];
  readonly tags: readonly TaggedWord[];
}

export interface GeneratedSurrealistCorpus {
  readonly fragments: readonly GeneratedSurrealistFragment[];
  readonly lastBuilt: string;
}

/**
 * Tokenize on whitespace + simple punctuation, preserving the original
 * casing for display but lowercasing for POS lookup.
 */
function tokenizeFragment(text: string): string[] {
  // Strip leading/trailing punctuation but keep inner word characters.
  return text
    .split(/\s+/)
    .map((tok) => tok.replace(/^[^\p{L}\p{N}'-]+|[^\p{L}\p{N}'-]+$/gu, ""))
    .filter((tok) => tok.length > 0);
}

const CONTENT_POS_PREFIXES = ["nn", "vb", "jj", "rb"] as const;

function isContentWord(pos: string): boolean {
  return CONTENT_POS_PREFIXES.some((p) => pos.startsWith(p));
}

/**
 * POS-tag a fragment via RiTa. Unknown words (nonsense surrealist
 * coinages like "borogoves", "tulgey", "gadji") get a `uh` tag —
 * we want to keep them regardless; their POS just isn't usable.
 *
 * Returns tokens unchanged (for chaining) plus per-content-word tags
 * with syllable counts so the runtime can do simple metrical choices
 * without ever loading RiTa itself.
 */
export function tagSurrealistFragment(fragment: SurrealistFragment): GeneratedSurrealistFragment {
  const tokens = tokenizeFragment(fragment.text);
  const tags: TaggedWord[] = [];
  for (const raw of tokens) {
    const word = raw.toLowerCase();
    const pos = posTag(word) || "uh";
    if (!isContentWord(pos)) continue;
    const syllables = countSyllables(word);
    tags.push({
      word,
      pos,
      // Non-dictionary words get syllables=0; treat that as 1 for display.
      syllables: syllables > 0 ? syllables : 1,
    });
  }
  return {
    id: fragment.id,
    text: fragment.text,
    source: fragment.source,
    year: fragment.year,
    derivative: fragment.derivative,
    tokens,
    tags,
  };
}

export function buildSurrealistCorpus(
  fragments: readonly SurrealistFragment[] = SURREALIST_FRAGMENTS,
  now: Date = new Date()
): GeneratedSurrealistCorpus {
  if (fragments.length < 30) {
    throw new Error(`Surrealist corpus must contain ≥ 30 fragments; got ${fragments.length}`);
  }
  const seenIds = new Set<string>();
  for (const frag of fragments) {
    if (seenIds.has(frag.id)) {
      throw new Error(`Duplicate surrealist fragment id: ${frag.id}`);
    }
    seenIds.add(frag.id);
    if (!frag.publicDomain) {
      throw new Error(`Fragment ${frag.id} is not marked publicDomain: true — refusing to ship it`);
    }
  }
  return {
    fragments: fragments.map(tagSurrealistFragment),
    lastBuilt: now.toISOString(),
  };
}

const SURREALIST_BANNER = [
  "// ============================================================================",
  "// DO NOT EDIT — generated by scripts/build-corpus.ts",
  "// Run `pnpm build-corpus` to regenerate this file from the fragment source.",
  "// Source of truth: scripts/sources/surrealist-fragments.ts",
  "// ============================================================================",
].join("\n");

// Legacy `renderSurrealistModule` removed — surrealist data lives in
// surrealist.json now, consumed via the thin accessor in surrealist.ts.

/**
 * Stable JSON for surrealist corpus — mirrors the corpus one. Consumers
 * go through `surrealist.ts` which wraps this JSON with types.
 */
export function renderSurrealistJson(corpus: GeneratedSurrealistCorpus): string {
  return `${JSON.stringify(corpus, null, 2)}\n`;
}

export function renderSurrealistAccessorModule(): string {
  return `${SURREALIST_BANNER}

import data from "./surrealist.json" with { type: "json" };

export interface TaggedWord {
  readonly word: string;
  readonly pos: string;
  readonly syllables: number;
}

export interface GeneratedSurrealistFragment {
  readonly id: string;
  readonly text: string;
  readonly source: string;
  readonly year: number;
  readonly derivative: boolean;
  readonly tokens: readonly string[];
  readonly tags: readonly TaggedWord[];
}

export interface GeneratedSurrealistCorpus {
  readonly fragments: readonly GeneratedSurrealistFragment[];
  readonly lastBuilt: string;
}

export const SURREALIST_CORPUS = data as GeneratedSurrealistCorpus;
`;
}

/**
 * Re-use the prior `lastBuilt` stamp when nothing else changed so the JSON
 * output is byte-stable across CI runs (no wall-clock-driven diffs).
 */
function stableJson<T extends { lastBuilt: string }>(
  data: T,
  previous: string | null,
  render: (d: T) => string
): string {
  if (previous === null) return render(data);
  const candidate = render({
    ...data,
    lastBuilt: extractJsonLastBuilt(previous) ?? data.lastBuilt,
  });
  if (candidate === previous) return previous;
  return render(data);
}

function extractJsonLastBuilt(source: string): string | null {
  const match = source.match(/"lastBuilt":\s*"([^"]+)"/);
  return match?.[1] ?? null;
}

function writeIfChanged(target: string, contents: string): boolean {
  const previous = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (previous === contents) return false;
  writeFileSync(target, contents, "utf8");
  return true;
}

function main(): void {
  // ── Corpus ────────────────────────────────────────────────────────────
  const corpus = buildCorpus();
  const corpusJsonTarget = resolveCorpusJsonPath();
  const corpusJsonPrev = existsSync(corpusJsonTarget)
    ? readFileSync(corpusJsonTarget, "utf8")
    : null;
  const corpusJsonOut = stableJson(corpus, corpusJsonPrev, renderCorpusJson);
  writeIfChanged(corpusJsonTarget, corpusJsonOut);
  writeIfChanged(resolveCorpusAccessorPath(), renderCorpusAccessorModule());
  console.log(
    `[build-corpus] wrote ${corpus.nouns.length} nouns + ${corpus.adjectives.length} adjectives → corpus.json`
  );

  // ── Surrealist ────────────────────────────────────────────────────────
  const surrealist = buildSurrealistCorpus();
  const surrealistJsonTarget = resolveSurrealistJsonPath();
  const surrealistJsonPrev = existsSync(surrealistJsonTarget)
    ? readFileSync(surrealistJsonTarget, "utf8")
    : null;
  const surrealistJsonOut = stableJson(surrealist, surrealistJsonPrev, renderSurrealistJson);
  writeIfChanged(surrealistJsonTarget, surrealistJsonOut);
  writeIfChanged(resolveSurrealistAccessorPath(), renderSurrealistAccessorModule());
  console.log(
    `[build-corpus] wrote ${surrealist.fragments.length} surrealist fragments → surrealist.json`
  );

  // ── Grammars ──────────────────────────────────────────────────────────
  const grammars = buildGrammars();
  const grammarsTarget = resolveGrammarsOutputPath();
  const grammarsPrev = existsSync(grammarsTarget) ? readFileSync(grammarsTarget, "utf8") : null;
  const grammarsOut = renderStableGrammarsJson(grammars, grammarsPrev);
  writeIfChanged(grammarsTarget, grammarsOut);
  console.log(
    `[build-corpus] wrote grammars.json to ${path.relative(process.cwd(), grammarsTarget)}`
  );
}

function resolveGrammarsOutputPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "grammars.json");
}

// Run as CLI unless imported for testing. tsx sets import.meta.url to the
// script path when invoked directly.
const isDirectRun = (() => {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return fileURLToPath(import.meta.url) === path.resolve(entry);
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  main();
}
