/**
 * build-corpus
 *
 * Reads the hand-authored lexicons under src/content/lexicon/, validates each
 * word's part-of-speech with RiTa, computes pluralization and syllable counts,
 * and emits a frozen build artifact at src/content/generated/corpus.ts.
 *
 * Runtime MUST NOT import rita. This script is the only place rita runs.
 *
 * Usage:
 *   pnpm build-corpus
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { RiTa } from "rita";

import { ADJECTIVES } from "../src/content/lexicon/adjectives.ts";
import { NOUNS } from "../src/content/lexicon/nouns.ts";
import { SURREALIST_FRAGMENTS, type SurrealistFragment } from "./sources/surrealist-fragments.ts";

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export interface GeneratedCorpus {
  readonly nouns: readonly GeneratedNoun[];
  readonly adjectives: readonly GeneratedAdjective[];
  readonly lastBuilt: string;
}

/**
 * Treat a word as a noun if RiTa's dictionary tags it as one, or if the
 * fallback Penn Treebank tagger assigns it an `nn*` tag. isNoun alone only
 * covers words in RiTa's internal dictionary — philosophical vocabulary
 * like "syllogism", "tautology", and "lemma" is reliably tagged by pos()
 * via LTS rules even when isNoun() is false.
 */
function isNounStrict(word: string): boolean {
  if (RiTa.isNoun(word)) return true;
  const tag = posTag(word);
  return tag.startsWith("nn");
}

function isAdjectiveStrict(word: string): boolean {
  if (RiTa.isAdjective(word)) return true;
  const tag = posTag(word);
  return tag === "jj" || tag.startsWith("jj");
}

function posTag(word: string): string {
  const raw = RiTa.pos(word);
  const tag = Array.isArray(raw) ? raw[0] : raw;
  return String(tag ?? "");
}

function countSyllables(word: string): number {
  const phonemes = RiTa.syllables(word);
  if (!phonemes) return 0;
  // RiTa returns phoneme groups separated by "/" — one group per syllable.
  return phonemes.split("/").filter((s) => s.length > 0).length;
}

export function buildCorpus(
  nouns: readonly string[] = NOUNS,
  adjectives: readonly string[] = ADJECTIVES,
  now: Date = new Date()
): GeneratedCorpus {
  const badNouns = nouns.filter((w) => !isNounStrict(w));
  if (badNouns.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-nouns — fix the lexicon: ${badNouns.join(", ")}`
    );
  }

  const badAdjectives = adjectives.filter((w) => !isAdjectiveStrict(w));
  if (badAdjectives.length > 0) {
    throw new Error(
      `RiTa rejected the following entries as non-adjectives — fix the lexicon: ${badAdjectives.join(", ")}`
    );
  }

  const processedNouns: GeneratedNoun[] = nouns.map((word) => {
    const plural = RiTa.pluralize(word);
    if (!plural) {
      throw new Error(`RiTa produced an empty plural for "${word}"`);
    }
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, plural, syllables };
  });

  const processedAdjectives: GeneratedAdjective[] = adjectives.map((word) => {
    const syllables = countSyllables(word);
    if (syllables <= 0) {
      throw new Error(`RiTa produced zero syllables for "${word}"`);
    }
    return { word, syllables };
  });

  return {
    nouns: processedNouns,
    adjectives: processedAdjectives,
    lastBuilt: now.toISOString(),
  };
}

const BANNER = [
  "// ============================================================================",
  "// DO NOT EDIT — generated by scripts/build-corpus.ts",
  "// Run `pnpm build-corpus` to regenerate this file from the lexicons.",
  "// Hand-edits will be overwritten and CI will flag stale output.",
  "// ============================================================================",
].join("\n");

export function renderCorpusModule(corpus: GeneratedCorpus): string {
  const nounLines = corpus.nouns
    .map(
      (n) =>
        `    { word: ${JSON.stringify(n.word)}, plural: ${JSON.stringify(n.plural)}, syllables: ${n.syllables} },`
    )
    .join("\n");
  const adjLines = corpus.adjectives
    .map((a) => `    { word: ${JSON.stringify(a.word)}, syllables: ${a.syllables} },`)
    .join("\n");

  return `${BANNER}

export interface GeneratedNoun {
  readonly word: string;
  readonly plural: string;
  readonly syllables: number;
}

export interface GeneratedAdjective {
  readonly word: string;
  readonly syllables: number;
}

export const GENERATED_CORPUS = {
  nouns: [
${nounLines}
  ],
  adjectives: [
${adjLines}
  ],
  lastBuilt: ${JSON.stringify(corpus.lastBuilt)},
} as const;

export type GeneratedCorpus = typeof GENERATED_CORPUS;
`;
}

function resolveOutputPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "corpus.ts");
}

function resolveSurrealistOutputPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "..", "src", "content", "generated", "surrealist.ts");
}

// ============================================================================
// Surrealist corpus
// ============================================================================

export interface TaggedWord {
  readonly word: string;
  readonly pos: string;
  readonly syllables: number;
}

export interface GeneratedSurrealistFragment {
  readonly id: string;
  readonly text: string;
  readonly source: string;
  readonly year: number;
  readonly derivative: boolean;
  readonly tokens: readonly string[];
  readonly tags: readonly TaggedWord[];
}

export interface GeneratedSurrealistCorpus {
  readonly fragments: readonly GeneratedSurrealistFragment[];
  readonly lastBuilt: string;
}

/**
 * Tokenize on whitespace + simple punctuation, preserving the original
 * casing for display but lowercasing for POS lookup.
 */
function tokenizeFragment(text: string): string[] {
  // Strip leading/trailing punctuation but keep inner word characters.
  return text
    .split(/\s+/)
    .map((tok) => tok.replace(/^[^\p{L}\p{N}'-]+|[^\p{L}\p{N}'-]+$/gu, ""))
    .filter((tok) => tok.length > 0);
}

const CONTENT_POS_PREFIXES = ["nn", "vb", "jj", "rb"] as const;

function isContentWord(pos: string): boolean {
  return CONTENT_POS_PREFIXES.some((p) => pos.startsWith(p));
}

/**
 * POS-tag a fragment via RiTa. Unknown words (nonsense surrealist
 * coinages like "borogoves", "tulgey", "gadji") get a `uh` tag —
 * we want to keep them regardless; their POS just isn't usable.
 *
 * Returns tokens unchanged (for chaining) plus per-content-word tags
 * with syllable counts so the runtime can do simple metrical choices
 * without ever loading RiTa itself.
 */
export function tagSurrealistFragment(fragment: SurrealistFragment): GeneratedSurrealistFragment {
  const tokens = tokenizeFragment(fragment.text);
  const tags: TaggedWord[] = [];
  for (const raw of tokens) {
    const word = raw.toLowerCase();
    const pos = posTag(word) || "uh";
    if (!isContentWord(pos)) continue;
    const syllables = countSyllables(word);
    tags.push({
      word,
      pos,
      // Non-dictionary words get syllables=0; treat that as 1 for display.
      syllables: syllables > 0 ? syllables : 1,
    });
  }
  return {
    id: fragment.id,
    text: fragment.text,
    source: fragment.source,
    year: fragment.year,
    derivative: fragment.derivative,
    tokens,
    tags,
  };
}

export function buildSurrealistCorpus(
  fragments: readonly SurrealistFragment[] = SURREALIST_FRAGMENTS,
  now: Date = new Date()
): GeneratedSurrealistCorpus {
  if (fragments.length < 30) {
    throw new Error(`Surrealist corpus must contain ≥ 30 fragments; got ${fragments.length}`);
  }
  const seenIds = new Set<string>();
  for (const frag of fragments) {
    if (seenIds.has(frag.id)) {
      throw new Error(`Duplicate surrealist fragment id: ${frag.id}`);
    }
    seenIds.add(frag.id);
    if (!frag.publicDomain) {
      throw new Error(`Fragment ${frag.id} is not marked publicDomain: true — refusing to ship it`);
    }
  }
  return {
    fragments: fragments.map(tagSurrealistFragment),
    lastBuilt: now.toISOString(),
  };
}

const SURREALIST_BANNER = [
  "// ============================================================================",
  "// DO NOT EDIT — generated by scripts/build-corpus.ts",
  "// Run `pnpm build-corpus` to regenerate this file from the fragment source.",
  "// Source of truth: scripts/sources/surrealist-fragments.ts",
  "// ============================================================================",
].join("\n");

export function renderSurrealistModule(corpus: GeneratedSurrealistCorpus): string {
  const fragLines = corpus.fragments
    .map((frag) => {
      const tokenJson = JSON.stringify(frag.tokens);
      const tagLines = frag.tags
        .map(
          (t) =>
            `      { word: ${JSON.stringify(t.word)}, pos: ${JSON.stringify(t.pos)}, syllables: ${t.syllables} },`
        )
        .join("\n");
      return `    {
      id: ${JSON.stringify(frag.id)},
      text: ${JSON.stringify(frag.text)},
      source: ${JSON.stringify(frag.source)},
      year: ${frag.year},
      derivative: ${frag.derivative},
      tokens: ${tokenJson},
      tags: [
${tagLines}
      ],
    },`;
    })
    .join("\n");

  return `${SURREALIST_BANNER}

export interface TaggedWord {
  readonly word: string;
  readonly pos: string;
  readonly syllables: number;
}

export interface GeneratedSurrealistFragment {
  readonly id: string;
  readonly text: string;
  readonly source: string;
  readonly year: number;
  readonly derivative: boolean;
  readonly tokens: readonly string[];
  readonly tags: readonly TaggedWord[];
}

export const SURREALIST_CORPUS = {
  fragments: [
${fragLines}
  ],
  lastBuilt: ${JSON.stringify(corpus.lastBuilt)},
} as const;

export type GeneratedSurrealistCorpus = typeof SURREALIST_CORPUS;
`;
}

export function renderStableSurrealistModule(
  corpus: GeneratedSurrealistCorpus,
  previous: string | null
): string {
  if (previous === null) return renderSurrealistModule(corpus);
  const candidateWithPrevStamp = renderSurrealistModule({
    ...corpus,
    lastBuilt: extractLastBuilt(previous) ?? corpus.lastBuilt,
  });
  if (candidateWithPrevStamp === previous) return previous;
  return renderSurrealistModule(corpus);
}

/**
 * Produce the final module text for a fresh corpus, re-using the previous
 * `lastBuilt` timestamp if nothing else changed. This keeps CI diffs driven by
 * real content changes rather than wall-clock drift.
 */
export function renderStableCorpusModule(corpus: GeneratedCorpus, previous: string | null): string {
  if (previous === null) return renderCorpusModule(corpus);
  const candidateWithPrevStamp = renderCorpusModule({
    ...corpus,
    lastBuilt: extractLastBuilt(previous) ?? corpus.lastBuilt,
  });
  // If swapping in the prior timestamp reproduces the previous file exactly,
  // nothing of substance has changed — keep the old output byte-for-byte.
  if (candidateWithPrevStamp === previous) return previous;
  return renderCorpusModule(corpus);
}

function extractLastBuilt(source: string): string | null {
  const match = source.match(/lastBuilt:\s*"([^"]+)"/);
  return match?.[1] ?? null;
}

function main(): void {
  const corpus = buildCorpus();
  const target = resolveOutputPath();
  const previous = existsSync(target) ? readFileSync(target, "utf8") : null;
  const output = renderStableCorpusModule(corpus, previous);
  writeFileSync(target, output, "utf8");
  console.log(
    `[build-corpus] wrote ${corpus.nouns.length} nouns and ${corpus.adjectives.length} adjectives to ${path.relative(process.cwd(), target)}`
  );

  const surrealist = buildSurrealistCorpus();
  const surrealistTarget = resolveSurrealistOutputPath();
  const surrealistPrev = existsSync(surrealistTarget)
    ? readFileSync(surrealistTarget, "utf8")
    : null;
  const surrealistOut = renderStableSurrealistModule(surrealist, surrealistPrev);
  writeFileSync(surrealistTarget, surrealistOut, "utf8");
  console.log(
    `[build-corpus] wrote ${surrealist.fragments.length} surrealist fragments to ${path.relative(process.cwd(), surrealistTarget)}`
  );
}

// Run as CLI unless imported for testing. tsx sets import.meta.url to the
// script path when invoked directly.
const isDirectRun = (() => {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return fileURLToPath(import.meta.url) === path.resolve(entry);
  } catch {
    return false;
  }
})();

if (isDirectRun) {
  main();
}
